### ISSUE TITLE
Creates error 500 when deleting entries in Dolibarr 16.x

### ISSUE THREAD

**Issue by dom-madrid** [ATM-Consulting/dolibarr_module_history#34]
**Bug**

When deleting a product or service line in propale/order/invoice for customers or providers, it generates an error 500 when confirming the deletion.

**Environment Version**
16.0.0/1/2/3

**Environment OS**
Ubuntu Server LTS 20.04.5

**Environment Web server**
Apache/2.4.41

**Environment PHP**
PHP 7.4.3

**Environment Database**
MySQL 8.0.31

**Environment URL(s)**
No response

**Expected and actual behavior**
Create a new invoice
Add a new product line
Delete the product line
Confirm deletion

Expected: product line removed

Actual behavior: blank page / error 500

**Steps to reproduce the behavior**
Add the History module
Activate the module
Create a new invoice
Add a new product line
Delete the product line
Confirm deletion

**Attached files**
No response

**Comment by atm-lena** [comment]
We don't see error now, I close the issue. 
If error reappears, please let us know.
